version: '3.8'

services: 
  mongo:  
    container_name: mongodb
    image: mongo:4.4.6 
    restart: always
    ports:  
    - "27017:27017"  
    volumes:  
    - $PWD/storage/mongodb:/data/db
    - $PWD/backups/mongodb:/backups
     